
// This file has been generated by the GUI designer. Do not modify.
namespace ColorManager
{
	internal partial class MyForm
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action quitAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Button btnCreate;
		
		private global::Gtk.Button btnDelete;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry tbName;
		
		private global::Gtk.Button butCr1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.ColorButton clrBtn1;
		
		private global::Gtk.ColorButton clrBtn10;
		
		private global::Gtk.ColorButton clrBtn2;
		
		private global::Gtk.ColorButton clrBtn3;
		
		private global::Gtk.ColorButton clrBtn4;
		
		private global::Gtk.ColorButton clrBtn5;
		
		private global::Gtk.ColorButton clrBtn6;
		
		private global::Gtk.ColorButton clrBtn7;
		
		private global::Gtk.ColorButton clrBtn8;
		
		private global::Gtk.ColorButton clrBtn9;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry tbClr;
		
		private global::Gtk.ColorSelection colorselection1;
		
		private global::Gtk.Label lblDebug;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ColorManager.MyForm
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.FileAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
			w1.Add (this.quitAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
			w1.Add (this.HelpAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "ColorManager.MyForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("Color Manager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ColorManager.MyForm.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='quitAction' action='quitAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Palette");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.hbox1.Add (this.combobox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.combobox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCreate = new global::Gtk.Button ();
			this.btnCreate.CanFocus = true;
			this.btnCreate.Name = "btnCreate";
			this.btnCreate.UseUnderline = true;
			this.btnCreate.Label = global::Mono.Unix.Catalog.GetString ("Create Palette");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnCreate.Image = w5;
			this.hbox1.Add (this.btnCreate);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnCreate]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.btnDelete.Image = w7;
			this.hbox1.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDelete]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter palette name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.tbName = new global::Gtk.Entry ();
			this.tbName.CanFocus = true;
			this.tbName.Name = "tbName";
			this.tbName.IsEditable = true;
			this.tbName.InvisibleChar = '●';
			this.hbox2.Add (this.tbName);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tbName]));
			w11.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.butCr1 = new global::Gtk.Button ();
			this.butCr1.CanFocus = true;
			this.butCr1.Name = "butCr1";
			this.butCr1.UseUnderline = true;
			this.butCr1.Label = global::Mono.Unix.Catalog.GetString ("Create");
			this.hbox2.Add (this.butCr1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.butCr1]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(7)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn1 = new global::Gtk.ColorButton ();
			this.clrBtn1.CanFocus = true;
			this.clrBtn1.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn1.Name = "clrBtn1";
			this.table1.Add (this.clrBtn1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn1]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn10 = new global::Gtk.ColorButton ();
			this.clrBtn10.CanFocus = true;
			this.clrBtn10.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn10.Name = "clrBtn10";
			this.table1.Add (this.clrBtn10);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn10]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(4));
			w15.RightAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn2 = new global::Gtk.ColorButton ();
			this.clrBtn2.CanFocus = true;
			this.clrBtn2.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn2.Name = "clrBtn2";
			this.table1.Add (this.clrBtn2);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn2]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn3 = new global::Gtk.ColorButton ();
			this.clrBtn3.CanFocus = true;
			this.clrBtn3.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn3.Name = "clrBtn3";
			this.table1.Add (this.clrBtn3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn3]));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn4 = new global::Gtk.ColorButton ();
			this.clrBtn4.CanFocus = true;
			this.clrBtn4.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn4.Name = "clrBtn4";
			this.table1.Add (this.clrBtn4);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn4]));
			w18.LeftAttach = ((uint)(3));
			w18.RightAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn5 = new global::Gtk.ColorButton ();
			this.clrBtn5.CanFocus = true;
			this.clrBtn5.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn5.Name = "clrBtn5";
			this.table1.Add (this.clrBtn5);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn5]));
			w19.LeftAttach = ((uint)(4));
			w19.RightAttach = ((uint)(5));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn6 = new global::Gtk.ColorButton ();
			this.clrBtn6.CanFocus = true;
			this.clrBtn6.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn6.Name = "clrBtn6";
			this.table1.Add (this.clrBtn6);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn6]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn7 = new global::Gtk.ColorButton ();
			this.clrBtn7.CanFocus = true;
			this.clrBtn7.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn7.Name = "clrBtn7";
			this.table1.Add (this.clrBtn7);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn7]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn8 = new global::Gtk.ColorButton ();
			this.clrBtn8.CanFocus = true;
			this.clrBtn8.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn8.Name = "clrBtn8";
			this.table1.Add (this.clrBtn8);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn8]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clrBtn9 = new global::Gtk.ColorButton ();
			this.clrBtn9.CanFocus = true;
			this.clrBtn9.Events = ((global::Gdk.EventMask)(784));
			this.clrBtn9.Name = "clrBtn9";
			this.table1.Add (this.clrBtn9);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.clrBtn9]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(3));
			w23.RightAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Color Code");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w24.LeftAttach = ((uint)(5));
			w24.RightAttach = ((uint)(6));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbClr = new global::Gtk.Entry ();
			this.tbClr.CanFocus = true;
			this.tbClr.Name = "tbClr";
			this.tbClr.IsEditable = true;
			this.tbClr.InvisibleChar = '•';
			this.table1.Add (this.tbClr);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbClr]));
			w25.LeftAttach = ((uint)(6));
			w25.RightAttach = ((uint)(7));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.colorselection1 = new global::Gtk.ColorSelection ();
			this.colorselection1.Name = "colorselection1";
			this.colorselection1.HasOpacityControl = true;
			this.vbox1.Add (this.colorselection1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.colorselection1]));
			w27.Position = 4;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblDebug = new global::Gtk.Label ();
			this.lblDebug.Name = "lblDebug";
			this.lblDebug.LabelProp = global::Mono.Unix.Catalog.GetString ("Ready");
			this.lblDebug.SingleLineMode = true;
			this.vbox1.Add (this.lblDebug);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblDebug]));
			w28.Position = 5;
			w28.Expand = false;
			w28.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 505;
			this.DefaultHeight = 415;
			this.Show ();
			this.combobox1.Changed += new global::System.EventHandler (this.OnCombobox1Changed);
			this.btnCreate.Clicked += new global::System.EventHandler (this.OnBtnCreateClicked);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.butCr1.Clicked += new global::System.EventHandler (this.OnButCr1Clicked);
			this.clrBtn9.ColorSet += new global::System.EventHandler (this.OnClrBtn9ColorSet);
			this.clrBtn8.ColorSet += new global::System.EventHandler (this.OnClrBtn8ColorSet);
			this.clrBtn7.ColorSet += new global::System.EventHandler (this.OnClrBtn7ColorSet);
			this.clrBtn6.ColorSet += new global::System.EventHandler (this.OnClrBtn6ColorSet);
			this.clrBtn5.ColorSet += new global::System.EventHandler (this.OnClrBtn5ColorSet);
			this.clrBtn4.ColorSet += new global::System.EventHandler (this.OnClrBtn4ColorSet);
			this.clrBtn3.ColorSet += new global::System.EventHandler (this.OnClrBtn3ColorSet);
			this.clrBtn2.ColorSet += new global::System.EventHandler (this.OnClrBtn2ColorSet);
			this.clrBtn10.ColorSet += new global::System.EventHandler (this.OnClrBtn10ColorSet);
			this.clrBtn1.ColorSet += new global::System.EventHandler (this.OnClrBtn1ColorSet);
		}
	}
}
