// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ColorManager {
    
    
    internal partial class MyForm {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action FileAction;
        
        private Gtk.Action quitAction;
        
        private Gtk.Action HelpAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.ComboBox combobox1;
        
        private Gtk.Button btnCreate;
        
        private Gtk.Button btnDelete;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label2;
        
        private Gtk.Entry tbName;
        
        private Gtk.Button butCr1;
        
        private Gtk.Table table1;
        
        private Gtk.ColorButton clrBtn1;
        
        private Gtk.ColorButton clrBtn10;
        
        private Gtk.ColorButton clrBtn2;
        
        private Gtk.ColorButton clrBtn3;
        
        private Gtk.ColorButton clrBtn4;
        
        private Gtk.ColorButton clrBtn5;
        
        private Gtk.ColorButton clrBtn6;
        
        private Gtk.ColorButton clrBtn7;
        
        private Gtk.ColorButton clrBtn8;
        
        private Gtk.ColorButton clrBtn9;
        
        private Gtk.Label label3;
        
        private Gtk.Entry tbClr;
        
        private Gtk.ColorSelection colorselection1;
        
        private Gtk.Label lblDebug;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ColorManager.MyForm
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("_File");
            w1.Add(this.FileAction, null);
            this.quitAction = new Gtk.Action("quitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.quitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            w1.Add(this.quitAction, null);
            this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("_Help"), null, null);
            this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("_Help");
            w1.Add(this.HelpAction, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "ColorManager.MyForm";
            this.Title = Mono.Unix.Catalog.GetString("Color Manager");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child ColorManager.MyForm.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='quitAction' action='quitAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Select Palette");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.combobox1 = Gtk.ComboBox.NewText();
            this.combobox1.Name = "combobox1";
            this.hbox1.Add(this.combobox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.combobox1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnCreate = new Gtk.Button();
            this.btnCreate.CanFocus = true;
            this.btnCreate.Name = "btnCreate";
            this.btnCreate.UseUnderline = true;
            // Container child btnCreate.Gtk.Container+ContainerChild
            Gtk.Alignment w5 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w6 = new Gtk.HBox();
            w6.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w7 = new Gtk.Image();
            w7.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w6.Add(w7);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w9 = new Gtk.Label();
            w9.LabelProp = Mono.Unix.Catalog.GetString("Create Palette");
            w9.UseUnderline = true;
            w6.Add(w9);
            w5.Add(w6);
            this.btnCreate.Add(w5);
            this.hbox1.Add(this.btnCreate);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnCreate]));
            w13.Position = 3;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnDelete = new Gtk.Button();
            this.btnDelete.CanFocus = true;
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.UseUnderline = true;
            // Container child btnDelete.Gtk.Container+ContainerChild
            Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w15 = new Gtk.HBox();
            w15.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w16 = new Gtk.Image();
            w16.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-close", Gtk.IconSize.Menu, 16);
            w15.Add(w16);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w18 = new Gtk.Label();
            w18.LabelProp = Mono.Unix.Catalog.GetString("Delete");
            w18.UseUnderline = true;
            w15.Add(w18);
            w14.Add(w15);
            this.btnDelete.Add(w14);
            this.hbox1.Add(this.btnDelete);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnDelete]));
            w22.Position = 4;
            w22.Expand = false;
            w22.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Enter palette name");
            this.hbox2.Add(this.label2);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.tbName = new Gtk.Entry();
            this.tbName.CanFocus = true;
            this.tbName.Name = "tbName";
            this.tbName.IsEditable = true;
            this.tbName.InvisibleChar = '●';
            this.hbox2.Add(this.tbName);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox2[this.tbName]));
            w25.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.butCr1 = new Gtk.Button();
            this.butCr1.CanFocus = true;
            this.butCr1.Name = "butCr1";
            this.butCr1.UseUnderline = true;
            this.butCr1.Label = Mono.Unix.Catalog.GetString("Create");
            this.hbox2.Add(this.butCr1);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox2[this.butCr1]));
            w26.Position = 2;
            w26.Expand = false;
            w26.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w27.Position = 2;
            w27.Expand = false;
            w27.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(7)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn1 = new Gtk.ColorButton();
            this.clrBtn1.CanFocus = true;
            this.clrBtn1.Events = ((Gdk.EventMask)(784));
            this.clrBtn1.Name = "clrBtn1";
            this.table1.Add(this.clrBtn1);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn1]));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn10 = new Gtk.ColorButton();
            this.clrBtn10.CanFocus = true;
            this.clrBtn10.Events = ((Gdk.EventMask)(784));
            this.clrBtn10.Name = "clrBtn10";
            this.table1.Add(this.clrBtn10);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn10]));
            w29.TopAttach = ((uint)(1));
            w29.BottomAttach = ((uint)(2));
            w29.LeftAttach = ((uint)(4));
            w29.RightAttach = ((uint)(5));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn2 = new Gtk.ColorButton();
            this.clrBtn2.CanFocus = true;
            this.clrBtn2.Events = ((Gdk.EventMask)(784));
            this.clrBtn2.Name = "clrBtn2";
            this.table1.Add(this.clrBtn2);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn2]));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn3 = new Gtk.ColorButton();
            this.clrBtn3.CanFocus = true;
            this.clrBtn3.Events = ((Gdk.EventMask)(784));
            this.clrBtn3.Name = "clrBtn3";
            this.table1.Add(this.clrBtn3);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn3]));
            w31.LeftAttach = ((uint)(2));
            w31.RightAttach = ((uint)(3));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn4 = new Gtk.ColorButton();
            this.clrBtn4.CanFocus = true;
            this.clrBtn4.Events = ((Gdk.EventMask)(784));
            this.clrBtn4.Name = "clrBtn4";
            this.table1.Add(this.clrBtn4);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn4]));
            w32.LeftAttach = ((uint)(3));
            w32.RightAttach = ((uint)(4));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn5 = new Gtk.ColorButton();
            this.clrBtn5.CanFocus = true;
            this.clrBtn5.Events = ((Gdk.EventMask)(784));
            this.clrBtn5.Name = "clrBtn5";
            this.table1.Add(this.clrBtn5);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn5]));
            w33.LeftAttach = ((uint)(4));
            w33.RightAttach = ((uint)(5));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn6 = new Gtk.ColorButton();
            this.clrBtn6.CanFocus = true;
            this.clrBtn6.Events = ((Gdk.EventMask)(784));
            this.clrBtn6.Name = "clrBtn6";
            this.table1.Add(this.clrBtn6);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn6]));
            w34.TopAttach = ((uint)(1));
            w34.BottomAttach = ((uint)(2));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn7 = new Gtk.ColorButton();
            this.clrBtn7.CanFocus = true;
            this.clrBtn7.Events = ((Gdk.EventMask)(784));
            this.clrBtn7.Name = "clrBtn7";
            this.table1.Add(this.clrBtn7);
            Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn7]));
            w35.TopAttach = ((uint)(1));
            w35.BottomAttach = ((uint)(2));
            w35.LeftAttach = ((uint)(1));
            w35.RightAttach = ((uint)(2));
            w35.XOptions = ((Gtk.AttachOptions)(4));
            w35.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn8 = new Gtk.ColorButton();
            this.clrBtn8.CanFocus = true;
            this.clrBtn8.Events = ((Gdk.EventMask)(784));
            this.clrBtn8.Name = "clrBtn8";
            this.table1.Add(this.clrBtn8);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn8]));
            w36.TopAttach = ((uint)(1));
            w36.BottomAttach = ((uint)(2));
            w36.LeftAttach = ((uint)(2));
            w36.RightAttach = ((uint)(3));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.clrBtn9 = new Gtk.ColorButton();
            this.clrBtn9.CanFocus = true;
            this.clrBtn9.Events = ((Gdk.EventMask)(784));
            this.clrBtn9.Name = "clrBtn9";
            this.table1.Add(this.clrBtn9);
            Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table1[this.clrBtn9]));
            w37.TopAttach = ((uint)(1));
            w37.BottomAttach = ((uint)(2));
            w37.LeftAttach = ((uint)(3));
            w37.RightAttach = ((uint)(4));
            w37.XOptions = ((Gtk.AttachOptions)(4));
            w37.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Color Code");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w38.LeftAttach = ((uint)(5));
            w38.RightAttach = ((uint)(6));
            w38.XOptions = ((Gtk.AttachOptions)(4));
            w38.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.tbClr = new Gtk.Entry();
            this.tbClr.CanFocus = true;
            this.tbClr.Name = "tbClr";
            this.tbClr.IsEditable = true;
            this.tbClr.InvisibleChar = '•';
            this.table1.Add(this.tbClr);
            Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table1[this.tbClr]));
            w39.LeftAttach = ((uint)(6));
            w39.RightAttach = ((uint)(7));
            w39.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w40.Position = 3;
            w40.Expand = false;
            w40.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.colorselection1 = new Gtk.ColorSelection();
            this.colorselection1.Name = "colorselection1";
            this.colorselection1.HasOpacityControl = true;
            this.vbox1.Add(this.colorselection1);
            Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox1[this.colorselection1]));
            w41.Position = 4;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lblDebug = new Gtk.Label();
            this.lblDebug.Name = "lblDebug";
            this.lblDebug.LabelProp = Mono.Unix.Catalog.GetString("Ready");
            this.lblDebug.SingleLineMode = true;
            this.vbox1.Add(this.lblDebug);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblDebug]));
            w42.Position = 5;
            w42.Expand = false;
            w42.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 505;
            this.DefaultHeight = 415;
            this.Show();
            this.combobox1.Changed += new System.EventHandler(this.OnCombobox1Changed);
            this.btnCreate.Clicked += new System.EventHandler(this.OnBtnCreateClicked);
            this.btnDelete.Clicked += new System.EventHandler(this.OnBtnDeleteClicked);
            this.butCr1.Clicked += new System.EventHandler(this.OnButCr1Clicked);
            this.clrBtn9.ColorSet += new System.EventHandler(this.OnClrBtn9ColorSet);
            this.clrBtn8.ColorSet += new System.EventHandler(this.OnClrBtn8ColorSet);
            this.clrBtn7.ColorSet += new System.EventHandler(this.OnClrBtn7ColorSet);
            this.clrBtn6.ColorSet += new System.EventHandler(this.OnClrBtn6ColorSet);
            this.clrBtn5.ColorSet += new System.EventHandler(this.OnClrBtn5ColorSet);
            this.clrBtn4.ColorSet += new System.EventHandler(this.OnClrBtn4ColorSet);
            this.clrBtn3.ColorSet += new System.EventHandler(this.OnClrBtn3ColorSet);
            this.clrBtn2.ColorSet += new System.EventHandler(this.OnClrBtn2ColorSet);
            this.clrBtn10.ColorSet += new System.EventHandler(this.OnClrBtn10ColorSet);
            this.clrBtn1.ColorSet += new System.EventHandler(this.OnClrBtn1ColorSet);
        }
    }
}
