
// This file has been generated by the GUI designer. Do not modify.
namespace Stetic
{
	internal class Gui
	{
		private static bool initialized;

		internal static void Initialize (Gtk.Widget iconRenderer)
		{
			if ((Stetic.Gui.initialized == false)) {
				Stetic.Gui.initialized = true;
			}
		}
	}

	internal class IconLoader
	{
		public static Gdk.Pixbuf LoadIcon (Gtk.Widget widget, string name, Gtk.IconSize size)
		{
			// Try rendering the icon from the widget first
			Gdk.Pixbuf res = null;
			try {
				res = widget.RenderIcon (name, size, null);
			} catch {
				res = null;
			}
			if (res != null) {
				return res;
			}
			int sz;
			int sy;
			global::Gtk.Icon.SizeLookup (size, out sz, out sy);
			try {
				return Gtk.IconTheme.Default.LoadIcon (name, sz, 0);
			} catch (System.Exception) {
				if (name != "gtk-missing-image") {
					return Stetic.IconLoader.LoadIcon (widget, "gtk-missing-image", size);
				} else {
					// Create a plain empty Pixbuf as a fallback instead of using deprecated Gdk.Pixmap/GC
					try {
						return new Gdk.Pixbuf (Gdk.Colorspace.Rgb, false, 8, sz, sz);
					} catch {
						return null;
					}
				}
			}
		}
	}

	internal class ActionGroups
	{
		public static Gtk.ActionGroup GetActionGroup (System.Type type)
		{
			return Stetic.ActionGroups.GetActionGroup (type.FullName);
		}

		public static Gtk.ActionGroup GetActionGroup (string name)
		{
			return null;
		}
	}
}
