// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action Help;
    
    private Gtk.Action AboutUs;
    
    private Gtk.Action help;
    
    private Gtk.Action colorPicker;
    
    private Gtk.Action selectColor;
    
    private Gtk.Action quit;
    
    private Gtk.Action File;
    
    private Gtk.Action quit1;
    
    private Gtk.Action Help1;
    
    private Gtk.Action Help2;
    
    private Gtk.Action selectColor1;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.ComboBoxEntry comboboxentry1;
    
    private Gtk.Button btnNew;
    
    private Gtk.Button button2;
    
    private Gtk.Button btnDelete;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label lblPaletteName;
    
    private Gtk.Entry entry1;
    
    private Gtk.Button btnAdd;
    
    private Gtk.Button btnUpdate;
    
    private Gtk.Button btnCancle;
    
    private Gtk.Table table1;
    
    private Gtk.ColorButton colorbutton1;
    
    private Gtk.ColorButton colorbutton10;
    
    private Gtk.ColorButton colorbutton11;
    
    private Gtk.ColorButton colorbutton12;
    
    private Gtk.ColorButton colorbutton13;
    
    private Gtk.ColorButton colorbutton14;
    
    private Gtk.ColorButton colorbutton15;
    
    private Gtk.ColorButton colorbutton16;
    
    private Gtk.ColorButton colorbutton2;
    
    private Gtk.ColorButton colorbutton3;
    
    private Gtk.ColorButton colorbutton4;
    
    private Gtk.ColorButton colorbutton5;
    
    private Gtk.ColorButton colorbutton6;
    
    private Gtk.ColorButton colorbutton7;
    
    private Gtk.ColorButton colorbutton8;
    
    private Gtk.ColorButton colorbutton9;
    
    private Gtk.Entry entry2;
    
    private Gtk.Entry entry4;
    
    private Gtk.Label label2;
    
    private Gtk.Label label3;
    
    private Gtk.ColorSelection colorselection1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.Help, null);
        this.AboutUs = new Gtk.Action("AboutUs", Mono.Unix.Catalog.GetString("About us"), null, null);
        this.AboutUs.ShortLabel = Mono.Unix.Catalog.GetString("About us");
        w1.Add(this.AboutUs, null);
        this.help = new Gtk.Action("help", Mono.Unix.Catalog.GetString("About us"), null, "gtk-help");
        this.help.ShortLabel = Mono.Unix.Catalog.GetString("_Help");
        w1.Add(this.help, null);
        this.colorPicker = new Gtk.Action("colorPicker", null, null, "gtk-color-picker");
        w1.Add(this.colorPicker, null);
        this.selectColor = new Gtk.Action("selectColor", Mono.Unix.Catalog.GetString("_Color"), null, "gtk-select-color");
        this.selectColor.ShortLabel = Mono.Unix.Catalog.GetString("_Color");
        w1.Add(this.selectColor, null);
        this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.quit, null);
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("  File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("  File");
        w1.Add(this.File, null);
        this.quit1 = new Gtk.Action("quit1", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quit1.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.quit1, null);
        this.Help1 = new Gtk.Action("Help1", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.Help1.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.Help1, null);
        this.Help2 = new Gtk.Action("Help2", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.Help2.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.Help2, null);
        this.selectColor1 = new Gtk.Action("selectColor1", Mono.Unix.Catalog.GetString("About Us"), null, "gtk-dialog-info");
        this.selectColor1.ShortLabel = Mono.Unix.Catalog.GetString("About Us");
        w1.Add(this.selectColor1, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("ColorPicker");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-select-color", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.DefaultWidth = 13;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='File' action='File'><menuitem name='quit1' action='quit1'/></menu><menu name='Help2' action='Help2'><menuitem name='selectColor1' action='selectColor1'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.comboboxentry1 = Gtk.ComboBoxEntry.NewText();
        this.comboboxentry1.Name = "comboboxentry1";
        this.hbox1.Add(this.comboboxentry1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.comboboxentry1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.btnNew = new Gtk.Button();
        this.btnNew.CanFocus = true;
        this.btnNew.Name = "btnNew";
        this.btnNew.UseUnderline = true;
        // Container child btnNew.Gtk.Container+ContainerChild
        Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w5 = new Gtk.HBox();
        w5.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w6 = new Gtk.Image();
        w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w5.Add(w6);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w8 = new Gtk.Label();
        w8.LabelProp = Mono.Unix.Catalog.GetString("New");
        w8.UseUnderline = true;
        w5.Add(w8);
        w4.Add(w5);
        this.btnNew.Add(w4);
        this.hbox1.Add(this.btnNew);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnNew]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        // Container child button2.Gtk.Container+ContainerChild
        Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w14 = new Gtk.HBox();
        w14.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w15 = new Gtk.Image();
        w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Menu, 16);
        w14.Add(w15);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w17 = new Gtk.Label();
        w17.LabelProp = Mono.Unix.Catalog.GetString("Edit");
        w17.UseUnderline = true;
        w14.Add(w17);
        w13.Add(w14);
        this.button2.Add(w13);
        this.hbox1.Add(this.button2);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox1[this.button2]));
        w21.Position = 2;
        w21.Expand = false;
        w21.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.btnDelete = new Gtk.Button();
        this.btnDelete.CanFocus = true;
        this.btnDelete.Name = "btnDelete";
        this.btnDelete.UseUnderline = true;
        // Container child btnDelete.Gtk.Container+ContainerChild
        Gtk.Alignment w22 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w23 = new Gtk.HBox();
        w23.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w24 = new Gtk.Image();
        w24.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-clear", Gtk.IconSize.Menu, 16);
        w23.Add(w24);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w26 = new Gtk.Label();
        w26.LabelProp = Mono.Unix.Catalog.GetString("Delete");
        w26.UseUnderline = true;
        w23.Add(w26);
        w22.Add(w23);
        this.btnDelete.Add(w22);
        this.hbox1.Add(this.btnDelete);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnDelete]));
        w30.Position = 3;
        w30.Expand = false;
        w30.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w31.Position = 1;
        w31.Expand = false;
        w31.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.lblPaletteName = new Gtk.Label();
        this.lblPaletteName.Name = "lblPaletteName";
        this.lblPaletteName.LabelProp = Mono.Unix.Catalog.GetString("Enter name for a new Palette:");
        this.hbox2.Add(this.lblPaletteName);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox2[this.lblPaletteName]));
        w32.Position = 0;
        w32.Expand = false;
        w32.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.entry1 = new Gtk.Entry();
        this.entry1.WidthRequest = 0;
        this.entry1.HeightRequest = 28;
        this.entry1.CanFocus = true;
        this.entry1.Name = "entry1";
        this.entry1.IsEditable = true;
        this.entry1.InvisibleChar = '•';
        this.hbox2.Add(this.entry1);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox2[this.entry1]));
        w33.Position = 1;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnAdd = new Gtk.Button();
        this.btnAdd.CanFocus = true;
        this.btnAdd.Name = "btnAdd";
        this.btnAdd.UseUnderline = true;
        this.btnAdd.Label = Mono.Unix.Catalog.GetString("Add");
        this.hbox2.Add(this.btnAdd);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnAdd]));
        w34.Position = 2;
        w34.Expand = false;
        w34.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnUpdate = new Gtk.Button();
        this.btnUpdate.CanFocus = true;
        this.btnUpdate.Name = "btnUpdate";
        this.btnUpdate.UseUnderline = true;
        this.btnUpdate.Label = Mono.Unix.Catalog.GetString("Update");
        this.hbox2.Add(this.btnUpdate);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnUpdate]));
        w35.Position = 3;
        w35.Expand = false;
        w35.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnCancle = new Gtk.Button();
        this.btnCancle.CanFocus = true;
        this.btnCancle.Name = "btnCancle";
        this.btnCancle.UseUnderline = true;
        this.btnCancle.Label = Mono.Unix.Catalog.GetString("Cancel");
        this.hbox2.Add(this.btnCancle);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnCancle]));
        w36.Position = 4;
        w36.Expand = false;
        w36.Fill = false;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w37.Position = 2;
        w37.Expand = false;
        w37.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.table1 = new Gtk.Table(((uint)(2)), ((uint)(10)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        this.table1.BorderWidth = ((uint)(12));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton1 = new Gtk.ColorButton();
        this.colorbutton1.CanDefault = true;
        this.colorbutton1.CanFocus = true;
        this.colorbutton1.Events = ((Gdk.EventMask)(788));
        this.colorbutton1.Name = "colorbutton1";
        this.colorbutton1.Relief = ((Gtk.ReliefStyle)(1));
        this.table1.Add(this.colorbutton1);
        Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton1]));
        w38.XOptions = ((Gtk.AttachOptions)(4));
        w38.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton10 = new Gtk.ColorButton();
        this.colorbutton10.CanFocus = true;
        this.colorbutton10.Events = ((Gdk.EventMask)(784));
        this.colorbutton10.Name = "colorbutton10";
        this.table1.Add(this.colorbutton10);
        Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton10]));
        w39.TopAttach = ((uint)(1));
        w39.BottomAttach = ((uint)(2));
        w39.LeftAttach = ((uint)(1));
        w39.RightAttach = ((uint)(2));
        w39.XOptions = ((Gtk.AttachOptions)(4));
        w39.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton11 = new Gtk.ColorButton();
        this.colorbutton11.CanFocus = true;
        this.colorbutton11.Events = ((Gdk.EventMask)(784));
        this.colorbutton11.Name = "colorbutton11";
        this.table1.Add(this.colorbutton11);
        Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton11]));
        w40.TopAttach = ((uint)(1));
        w40.BottomAttach = ((uint)(2));
        w40.LeftAttach = ((uint)(2));
        w40.RightAttach = ((uint)(3));
        w40.XOptions = ((Gtk.AttachOptions)(4));
        w40.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton12 = new Gtk.ColorButton();
        this.colorbutton12.CanFocus = true;
        this.colorbutton12.Events = ((Gdk.EventMask)(784));
        this.colorbutton12.Name = "colorbutton12";
        this.table1.Add(this.colorbutton12);
        Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton12]));
        w41.TopAttach = ((uint)(1));
        w41.BottomAttach = ((uint)(2));
        w41.LeftAttach = ((uint)(3));
        w41.RightAttach = ((uint)(4));
        w41.XOptions = ((Gtk.AttachOptions)(4));
        w41.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton13 = new Gtk.ColorButton();
        this.colorbutton13.CanFocus = true;
        this.colorbutton13.Events = ((Gdk.EventMask)(784));
        this.colorbutton13.Name = "colorbutton13";
        this.table1.Add(this.colorbutton13);
        Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton13]));
        w42.TopAttach = ((uint)(1));
        w42.BottomAttach = ((uint)(2));
        w42.LeftAttach = ((uint)(4));
        w42.RightAttach = ((uint)(5));
        w42.XOptions = ((Gtk.AttachOptions)(4));
        w42.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton14 = new Gtk.ColorButton();
        this.colorbutton14.CanFocus = true;
        this.colorbutton14.Events = ((Gdk.EventMask)(784));
        this.colorbutton14.Name = "colorbutton14";
        this.table1.Add(this.colorbutton14);
        Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton14]));
        w43.TopAttach = ((uint)(1));
        w43.BottomAttach = ((uint)(2));
        w43.LeftAttach = ((uint)(5));
        w43.RightAttach = ((uint)(6));
        w43.XOptions = ((Gtk.AttachOptions)(4));
        w43.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton15 = new Gtk.ColorButton();
        this.colorbutton15.CanFocus = true;
        this.colorbutton15.Events = ((Gdk.EventMask)(784));
        this.colorbutton15.Name = "colorbutton15";
        this.table1.Add(this.colorbutton15);
        Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton15]));
        w44.TopAttach = ((uint)(1));
        w44.BottomAttach = ((uint)(2));
        w44.LeftAttach = ((uint)(6));
        w44.RightAttach = ((uint)(7));
        w44.XOptions = ((Gtk.AttachOptions)(4));
        w44.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton16 = new Gtk.ColorButton();
        this.colorbutton16.CanFocus = true;
        this.colorbutton16.Events = ((Gdk.EventMask)(784));
        this.colorbutton16.Name = "colorbutton16";
        this.table1.Add(this.colorbutton16);
        Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton16]));
        w45.TopAttach = ((uint)(1));
        w45.BottomAttach = ((uint)(2));
        w45.LeftAttach = ((uint)(7));
        w45.RightAttach = ((uint)(8));
        w45.XOptions = ((Gtk.AttachOptions)(4));
        w45.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton2 = new Gtk.ColorButton();
        this.colorbutton2.CanFocus = true;
        this.colorbutton2.Events = ((Gdk.EventMask)(784));
        this.colorbutton2.Name = "colorbutton2";
        this.table1.Add(this.colorbutton2);
        Gtk.Table.TableChild w46 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton2]));
        w46.LeftAttach = ((uint)(1));
        w46.RightAttach = ((uint)(2));
        w46.XOptions = ((Gtk.AttachOptions)(4));
        w46.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton3 = new Gtk.ColorButton();
        this.colorbutton3.CanFocus = true;
        this.colorbutton3.Events = ((Gdk.EventMask)(784));
        this.colorbutton3.Name = "colorbutton3";
        this.table1.Add(this.colorbutton3);
        Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton3]));
        w47.LeftAttach = ((uint)(2));
        w47.RightAttach = ((uint)(3));
        w47.XOptions = ((Gtk.AttachOptions)(4));
        w47.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton4 = new Gtk.ColorButton();
        this.colorbutton4.CanFocus = true;
        this.colorbutton4.Events = ((Gdk.EventMask)(784));
        this.colorbutton4.Name = "colorbutton4";
        this.table1.Add(this.colorbutton4);
        Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton4]));
        w48.LeftAttach = ((uint)(3));
        w48.RightAttach = ((uint)(4));
        w48.XOptions = ((Gtk.AttachOptions)(4));
        w48.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton5 = new Gtk.ColorButton();
        this.colorbutton5.CanFocus = true;
        this.colorbutton5.Events = ((Gdk.EventMask)(784));
        this.colorbutton5.Name = "colorbutton5";
        this.table1.Add(this.colorbutton5);
        Gtk.Table.TableChild w49 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton5]));
        w49.LeftAttach = ((uint)(4));
        w49.RightAttach = ((uint)(5));
        w49.XOptions = ((Gtk.AttachOptions)(4));
        w49.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton6 = new Gtk.ColorButton();
        this.colorbutton6.CanFocus = true;
        this.colorbutton6.Events = ((Gdk.EventMask)(784));
        this.colorbutton6.Name = "colorbutton6";
        this.table1.Add(this.colorbutton6);
        Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton6]));
        w50.LeftAttach = ((uint)(5));
        w50.RightAttach = ((uint)(6));
        w50.XOptions = ((Gtk.AttachOptions)(4));
        w50.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton7 = new Gtk.ColorButton();
        this.colorbutton7.CanFocus = true;
        this.colorbutton7.Events = ((Gdk.EventMask)(784));
        this.colorbutton7.Name = "colorbutton7";
        this.table1.Add(this.colorbutton7);
        Gtk.Table.TableChild w51 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton7]));
        w51.LeftAttach = ((uint)(6));
        w51.RightAttach = ((uint)(7));
        w51.XOptions = ((Gtk.AttachOptions)(4));
        w51.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton8 = new Gtk.ColorButton();
        this.colorbutton8.CanFocus = true;
        this.colorbutton8.Events = ((Gdk.EventMask)(784));
        this.colorbutton8.Name = "colorbutton8";
        this.table1.Add(this.colorbutton8);
        Gtk.Table.TableChild w52 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton8]));
        w52.LeftAttach = ((uint)(7));
        w52.RightAttach = ((uint)(8));
        w52.XOptions = ((Gtk.AttachOptions)(4));
        w52.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.colorbutton9 = new Gtk.ColorButton();
        this.colorbutton9.CanFocus = true;
        this.colorbutton9.Events = ((Gdk.EventMask)(784));
        this.colorbutton9.Name = "colorbutton9";
        this.table1.Add(this.colorbutton9);
        Gtk.Table.TableChild w53 = ((Gtk.Table.TableChild)(this.table1[this.colorbutton9]));
        w53.TopAttach = ((uint)(1));
        w53.BottomAttach = ((uint)(2));
        w53.XOptions = ((Gtk.AttachOptions)(4));
        w53.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.entry2 = new Gtk.Entry();
        this.entry2.CanFocus = true;
        this.entry2.Name = "entry2";
        this.entry2.IsEditable = false;
        this.entry2.WidthChars = 8;
        this.entry2.InvisibleChar = '•';
        this.table1.Add(this.entry2);
        Gtk.Table.TableChild w54 = ((Gtk.Table.TableChild)(this.table1[this.entry2]));
        w54.TopAttach = ((uint)(1));
        w54.BottomAttach = ((uint)(2));
        w54.LeftAttach = ((uint)(9));
        w54.RightAttach = ((uint)(10));
        w54.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.entry4 = new Gtk.Entry();
        this.entry4.CanFocus = true;
        this.entry4.Name = "entry4";
        this.entry4.IsEditable = false;
        this.entry4.WidthChars = 8;
        this.entry4.MaxLength = 8;
        this.entry4.InvisibleChar = '•';
        this.table1.Add(this.entry4);
        Gtk.Table.TableChild w55 = ((Gtk.Table.TableChild)(this.table1[this.entry4]));
        w55.LeftAttach = ((uint)(9));
        w55.RightAttach = ((uint)(10));
        w55.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("WebSnap");
        this.table1.Add(this.label2);
        Gtk.Table.TableChild w56 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
        w56.TopAttach = ((uint)(1));
        w56.BottomAttach = ((uint)(2));
        w56.LeftAttach = ((uint)(8));
        w56.RightAttach = ((uint)(9));
        w56.XOptions = ((Gtk.AttachOptions)(4));
        w56.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("#");
        this.table1.Add(this.label3);
        Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
        w57.LeftAttach = ((uint)(8));
        w57.RightAttach = ((uint)(9));
        w57.XOptions = ((Gtk.AttachOptions)(4));
        w57.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox1.Add(this.table1);
        Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
        w58.Position = 3;
        w58.Expand = false;
        w58.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.colorselection1 = new Gtk.ColorSelection();
        this.colorselection1.Name = "colorselection1";
        this.colorselection1.HasOpacityControl = true;
        this.vbox1.Add(this.colorselection1);
        Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.vbox1[this.colorselection1]));
        w59.Position = 4;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultHeight = 511;
        this.btnUpdate.Hide();
        this.hbox2.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.quit1.Activated += new System.EventHandler(this.QuitClicked);
        this.selectColor1.Activated += new System.EventHandler(this.AboutusClicked);
        this.comboboxentry1.Changed += new System.EventHandler(this.Cmb_Changed);
        this.btnNew.Clicked += new System.EventHandler(this.OnBtnNewClicked);
        this.button2.Clicked += new System.EventHandler(this.onBtnEditClicked);
        this.btnDelete.Clicked += new System.EventHandler(this.onBtnDeleteClicked);
        this.btnAdd.Clicked += new System.EventHandler(this.add_Click);
        this.btnUpdate.Clicked += new System.EventHandler(this.btnUpdateClick);
        this.btnCancle.Clicked += new System.EventHandler(this.OnBtnCancleClicked);
        this.colorbutton9.ColorSet += new System.EventHandler(this.OnColorbutton9ColorSet);
        this.colorbutton8.ColorSet += new System.EventHandler(this.OnColorbutton8ColorSet);
        this.colorbutton7.ColorSet += new System.EventHandler(this.OnColorbutton7ColorSet);
        this.colorbutton6.ColorSet += new System.EventHandler(this.OnColorbutton6ColorSet);
        this.colorbutton5.ColorSet += new System.EventHandler(this.OnColorbutton5ColorSet);
        this.colorbutton4.ColorSet += new System.EventHandler(this.OnColorbutton4ColorSet);
        this.colorbutton3.ColorSet += new System.EventHandler(this.OnColorbutton3ColorSet);
        this.colorbutton2.ColorSet += new System.EventHandler(this.OnColorbutton2ColorSet);
        this.colorbutton16.ColorSet += new System.EventHandler(this.OnColorbutton16ColorSet);
        this.colorbutton15.ColorSet += new System.EventHandler(this.OnColorbutton15ColorSet);
        this.colorbutton14.ColorSet += new System.EventHandler(this.OnColorbutton14ColorSet);
        this.colorbutton13.ColorSet += new System.EventHandler(this.OnColorbutton13ColorSet);
        this.colorbutton12.ColorSet += new System.EventHandler(this.OnColorbutton12ColorSet);
        this.colorbutton11.ColorSet += new System.EventHandler(this.OnColorbutton11ColorSet);
        this.colorbutton10.ColorSet += new System.EventHandler(this.OnColorbutton10ColorSet);
        this.colorbutton1.Clicked += new System.EventHandler(this.OnCbtnClick);
        this.colorbutton1.ColorSet += new System.EventHandler(this.OnColorbutton1ColorSet);
        this.colorbutton1.Released += new System.EventHandler(this.cbtn_Released);
    }
}
