
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action Help;
	
	private global::Gtk.Action AboutUs;
	
	private global::Gtk.Action help;
	
	private global::Gtk.Action colorPicker;
	
	private global::Gtk.Action selectColor;
	
	private global::Gtk.Action quit;
	
	private global::Gtk.Action File;
	
	private global::Gtk.Action quit1;
	
	private global::Gtk.Action Help1;
	
	private global::Gtk.Action Help2;
	
	private global::Gtk.Action selectColor1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ComboBoxEntry comboboxentry1;
	
	private global::Gtk.Button btnNew;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button btnDelete;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label lblPaletteName;
	
	private global::Gtk.Entry entry1;
	
	private global::Gtk.Button btnAdd;
	
	private global::Gtk.Button btnUpdate;
	
	private global::Gtk.Button btnCancle;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.ColorButton colorbutton1;
	
	private global::Gtk.ColorButton colorbutton10;
	
	private global::Gtk.ColorButton colorbutton11;
	
	private global::Gtk.ColorButton colorbutton12;
	
	private global::Gtk.ColorButton colorbutton13;
	
	private global::Gtk.ColorButton colorbutton14;
	
	private global::Gtk.ColorButton colorbutton15;
	
	private global::Gtk.ColorButton colorbutton16;
	
	private global::Gtk.ColorButton colorbutton2;
	
	private global::Gtk.ColorButton colorbutton3;
	
	private global::Gtk.ColorButton colorbutton4;
	
	private global::Gtk.ColorButton colorbutton5;
	
	private global::Gtk.ColorButton colorbutton6;
	
	private global::Gtk.ColorButton colorbutton7;
	
	private global::Gtk.ColorButton colorbutton8;
	
	private global::Gtk.ColorButton colorbutton9;
	
	private global::Gtk.Entry entry2;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ColorSelection colorselection1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.Help = new global::Gtk.Action ("Help", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.Help.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.Help, null);
		this.AboutUs = new global::Gtk.Action ("AboutUs", global::Mono.Unix.Catalog.GetString ("About us"), null, null);
		this.AboutUs.ShortLabel = global::Mono.Unix.Catalog.GetString ("About us");
		w1.Add (this.AboutUs, null);
		this.help = new global::Gtk.Action ("help", global::Mono.Unix.Catalog.GetString ("About us"), null, "gtk-help");
		this.help.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.help, null);
		this.colorPicker = new global::Gtk.Action ("colorPicker", null, null, "gtk-color-picker");
		w1.Add (this.colorPicker, null);
		this.selectColor = new global::Gtk.Action ("selectColor", global::Mono.Unix.Catalog.GetString ("_Color"), null, "gtk-select-color");
		this.selectColor.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Color");
		w1.Add (this.selectColor, null);
		this.quit = new global::Gtk.Action ("quit", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quit.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quit, null);
		this.File = new global::Gtk.Action ("File", global::Mono.Unix.Catalog.GetString ("  File"), null, null);
		this.File.ShortLabel = global::Mono.Unix.Catalog.GetString ("  File");
		w1.Add (this.File, null);
		this.quit1 = new global::Gtk.Action ("quit1", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quit1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quit1, null);
		this.Help1 = new global::Gtk.Action ("Help1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.Help1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.Help1, null);
		this.Help2 = new global::Gtk.Action ("Help2", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.Help2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.Help2, null);
		this.selectColor1 = new global::Gtk.Action ("selectColor1", global::Mono.Unix.Catalog.GetString ("About Us"), null, "gtk-dialog-info");
		this.selectColor1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About Us");
		w1.Add (this.selectColor1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("ColorPicker");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-color", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 13;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='File' action='File'><menuitem name='quit1' action='quit1'/></menu><menu name='Help2' action='Help2'><menuitem name='selectColor1' action='selectColor1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxentry1.Name = "comboboxentry1";
		this.hbox1.Add (this.comboboxentry1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxentry1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnNew = new global::Gtk.Button ();
		this.btnNew.CanFocus = true;
		this.btnNew.Name = "btnNew";
		this.btnNew.UseUnderline = true;
		this.btnNew.Label = global::Mono.Unix.Catalog.GetString ("New");
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		this.btnNew.Image = w4;
		this.hbox1.Add (this.btnNew);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnNew]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Edit");
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.button2.Image = w6;
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnDelete = new global::Gtk.Button ();
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
		global::Gtk.Image w8 = new global::Gtk.Image ();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
		this.btnDelete.Image = w8;
		this.hbox1.Add (this.btnDelete);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDelete]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblPaletteName = new global::Gtk.Label ();
		this.lblPaletteName.Name = "lblPaletteName";
		this.lblPaletteName.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter name for a new Palette:");
		this.hbox2.Add (this.lblPaletteName);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblPaletteName]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.WidthRequest = 0;
		this.entry1.HeightRequest = 28;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.hbox2.Add (this.entry1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry1]));
		w12.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnAdd = new global::Gtk.Button ();
		this.btnAdd.CanFocus = true;
		this.btnAdd.Name = "btnAdd";
		this.btnAdd.UseUnderline = true;
		this.btnAdd.Label = global::Mono.Unix.Catalog.GetString ("Add");
		this.hbox2.Add (this.btnAdd);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnAdd]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnUpdate = new global::Gtk.Button ();
		this.btnUpdate.CanFocus = true;
		this.btnUpdate.Name = "btnUpdate";
		this.btnUpdate.UseUnderline = true;
		this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.hbox2.Add (this.btnUpdate);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnUpdate]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnCancle = new global::Gtk.Button ();
		this.btnCancle.CanFocus = true;
		this.btnCancle.Name = "btnCancle";
		this.btnCancle.UseUnderline = true;
		this.btnCancle.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.hbox2.Add (this.btnCancle);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnCancle]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(10)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(12));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton1 = new global::Gtk.ColorButton ();
		this.colorbutton1.CanDefault = true;
		this.colorbutton1.CanFocus = true;
		this.colorbutton1.Events = ((global::Gdk.EventMask)(788));
		this.colorbutton1.Name = "colorbutton1";
		this.colorbutton1.Relief = ((global::Gtk.ReliefStyle)(1));
		this.table1.Add (this.colorbutton1);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton1]));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton10 = new global::Gtk.ColorButton ();
		this.colorbutton10.CanFocus = true;
		this.colorbutton10.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton10.Name = "colorbutton10";
		this.table1.Add (this.colorbutton10);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton10]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton11 = new global::Gtk.ColorButton ();
		this.colorbutton11.CanFocus = true;
		this.colorbutton11.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton11.Name = "colorbutton11";
		this.table1.Add (this.colorbutton11);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton11]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton12 = new global::Gtk.ColorButton ();
		this.colorbutton12.CanFocus = true;
		this.colorbutton12.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton12.Name = "colorbutton12";
		this.table1.Add (this.colorbutton12);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton12]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton13 = new global::Gtk.ColorButton ();
		this.colorbutton13.CanFocus = true;
		this.colorbutton13.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton13.Name = "colorbutton13";
		this.table1.Add (this.colorbutton13);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton13]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.LeftAttach = ((uint)(4));
		w21.RightAttach = ((uint)(5));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton14 = new global::Gtk.ColorButton ();
		this.colorbutton14.CanFocus = true;
		this.colorbutton14.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton14.Name = "colorbutton14";
		this.table1.Add (this.colorbutton14);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton14]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.LeftAttach = ((uint)(5));
		w22.RightAttach = ((uint)(6));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton15 = new global::Gtk.ColorButton ();
		this.colorbutton15.CanFocus = true;
		this.colorbutton15.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton15.Name = "colorbutton15";
		this.table1.Add (this.colorbutton15);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton15]));
		w23.TopAttach = ((uint)(1));
		w23.BottomAttach = ((uint)(2));
		w23.LeftAttach = ((uint)(6));
		w23.RightAttach = ((uint)(7));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton16 = new global::Gtk.ColorButton ();
		this.colorbutton16.CanFocus = true;
		this.colorbutton16.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton16.Name = "colorbutton16";
		this.table1.Add (this.colorbutton16);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton16]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(7));
		w24.RightAttach = ((uint)(8));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton2 = new global::Gtk.ColorButton ();
		this.colorbutton2.CanFocus = true;
		this.colorbutton2.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton2.Name = "colorbutton2";
		this.table1.Add (this.colorbutton2);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton2]));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton3 = new global::Gtk.ColorButton ();
		this.colorbutton3.CanFocus = true;
		this.colorbutton3.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton3.Name = "colorbutton3";
		this.table1.Add (this.colorbutton3);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton3]));
		w26.LeftAttach = ((uint)(2));
		w26.RightAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton4 = new global::Gtk.ColorButton ();
		this.colorbutton4.CanFocus = true;
		this.colorbutton4.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton4.Name = "colorbutton4";
		this.table1.Add (this.colorbutton4);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton4]));
		w27.LeftAttach = ((uint)(3));
		w27.RightAttach = ((uint)(4));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton5 = new global::Gtk.ColorButton ();
		this.colorbutton5.CanFocus = true;
		this.colorbutton5.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton5.Name = "colorbutton5";
		this.table1.Add (this.colorbutton5);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton5]));
		w28.LeftAttach = ((uint)(4));
		w28.RightAttach = ((uint)(5));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton6 = new global::Gtk.ColorButton ();
		this.colorbutton6.CanFocus = true;
		this.colorbutton6.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton6.Name = "colorbutton6";
		this.table1.Add (this.colorbutton6);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton6]));
		w29.LeftAttach = ((uint)(5));
		w29.RightAttach = ((uint)(6));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton7 = new global::Gtk.ColorButton ();
		this.colorbutton7.CanFocus = true;
		this.colorbutton7.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton7.Name = "colorbutton7";
		this.table1.Add (this.colorbutton7);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton7]));
		w30.LeftAttach = ((uint)(6));
		w30.RightAttach = ((uint)(7));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton8 = new global::Gtk.ColorButton ();
		this.colorbutton8.CanFocus = true;
		this.colorbutton8.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton8.Name = "colorbutton8";
		this.table1.Add (this.colorbutton8);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton8]));
		w31.LeftAttach = ((uint)(7));
		w31.RightAttach = ((uint)(8));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.colorbutton9 = new global::Gtk.ColorButton ();
		this.colorbutton9.CanFocus = true;
		this.colorbutton9.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton9.Name = "colorbutton9";
		this.table1.Add (this.colorbutton9);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.colorbutton9]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = false;
		this.entry2.WidthChars = 8;
		this.entry2.InvisibleChar = '•';
		this.table1.Add (this.entry2);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry2]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(9));
		w33.RightAttach = ((uint)(10));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = false;
		this.entry4.WidthChars = 8;
		this.entry4.MaxLength = 8;
		this.entry4.InvisibleChar = '•';
		this.table1.Add (this.entry4);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry4]));
		w34.LeftAttach = ((uint)(9));
		w34.RightAttach = ((uint)(10));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("WebSnap");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.LeftAttach = ((uint)(8));
		w35.RightAttach = ((uint)(9));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("#");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w36.LeftAttach = ((uint)(8));
		w36.RightAttach = ((uint)(9));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w37.Position = 3;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.colorselection1 = new global::Gtk.ColorSelection ();
		this.colorselection1.Name = "colorselection1";
		this.colorselection1.HasOpacityControl = true;
		this.vbox1.Add (this.colorselection1);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.colorselection1]));
		w38.Position = 4;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 511;
		this.btnUpdate.Hide ();
		this.hbox2.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quit1.Activated += new global::System.EventHandler (this.QuitClicked);
		this.selectColor1.Activated += new global::System.EventHandler (this.AboutusClicked);
		this.comboboxentry1.Changed += new global::System.EventHandler (this.Cmb_Changed);
		this.btnNew.Clicked += new global::System.EventHandler (this.OnBtnNewClicked);
		this.button2.Clicked += new global::System.EventHandler (this.onBtnEditClicked);
		this.btnDelete.Clicked += new global::System.EventHandler (this.onBtnDeleteClicked);
		this.btnAdd.Clicked += new global::System.EventHandler (this.add_Click);
		this.btnUpdate.Clicked += new global::System.EventHandler (this.btnUpdateClick);
		this.btnCancle.Clicked += new global::System.EventHandler (this.OnBtnCancleClicked);
		this.colorbutton9.ColorSet += new global::System.EventHandler (this.OnColorbutton9ColorSet);
		this.colorbutton8.ColorSet += new global::System.EventHandler (this.OnColorbutton8ColorSet);
		this.colorbutton7.ColorSet += new global::System.EventHandler (this.OnColorbutton7ColorSet);
		this.colorbutton6.ColorSet += new global::System.EventHandler (this.OnColorbutton6ColorSet);
		this.colorbutton5.ColorSet += new global::System.EventHandler (this.OnColorbutton5ColorSet);
		this.colorbutton4.ColorSet += new global::System.EventHandler (this.OnColorbutton4ColorSet);
		this.colorbutton3.ColorSet += new global::System.EventHandler (this.OnColorbutton3ColorSet);
		this.colorbutton2.ColorSet += new global::System.EventHandler (this.OnColorbutton2ColorSet);
		this.colorbutton16.ColorSet += new global::System.EventHandler (this.OnColorbutton16ColorSet);
		this.colorbutton15.ColorSet += new global::System.EventHandler (this.OnColorbutton15ColorSet);
		this.colorbutton14.ColorSet += new global::System.EventHandler (this.OnColorbutton14ColorSet);
		this.colorbutton13.ColorSet += new global::System.EventHandler (this.OnColorbutton13ColorSet);
		this.colorbutton12.ColorSet += new global::System.EventHandler (this.OnColorbutton12ColorSet);
		this.colorbutton11.ColorSet += new global::System.EventHandler (this.OnColorbutton11ColorSet);
		this.colorbutton10.ColorSet += new global::System.EventHandler (this.OnColorbutton10ColorSet);
		this.colorbutton1.Clicked += new global::System.EventHandler (this.OnCbtnClick);
		this.colorbutton1.ColorSet += new global::System.EventHandler (this.OnColorbutton1ColorSet);
		this.colorbutton1.Released += new global::System.EventHandler (this.cbtn_Released);
	}
}
