//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Linq;
using CommunityToolkit.Mvvm.ComponentModel;

namespace ColorManager
{
	public partial class MyColor : ObservableObject
	{
		[ObservableProperty]
		private string colorName = string.Empty;

		[ObservableProperty]
		private string hex = "FFFFFF";

		public MyColor()
		{
		}

		public XElement ToXml()
		{
			return new XElement("Color", new XAttribute("hex", Hex));
		}

		public void FromXml(XElement xelem)
		{
			var hexAttr = xelem.Attribute("hex");
			if (hexAttr != null)
			{
				Hex = hexAttr.Value;
			}
			
			var nameAttr = xelem.Attribute("name");
			if (nameAttr != null)
			{
				ColorName = nameAttr.Value;
			}
		}		
	}
}
